### ISSUE TITLE
Panic when grouping imports

### ISSUE THREAD

**Issue by aarongreenlee** [palantir/go-ptimports#66]
## What happened?

I observe the following panic when working with `godel`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14601c9]

goroutine 1 [running]:
github.com/palantir/godel-format-asset-ptimports/generated_src/internal/github.com/palantir/go-ptimports/v2/ptimports.groupImports.func1(0xc0002d00f3, 0xb, 0xf3f, 0x0, 0xc000277f00, 0xf3)
	/go/src/github.com/palantir/godel-format-asset-ptimports/generated_src/internal/github.com/palantir/go-ptimports/v2/ptimports/imports.go:193 +0x59
regexp.(*Regexp).ReplaceAllFunc.func1(0xc000277f00, 0xf3, 0x100, 0xc0002c6d50, 0x2, 0x2, 0x0, 0x100, 0x0)
	/usr/local/go/src/regexp/regexp.go:681 +0x95
regexp.(*Regexp).replaceAll(0xc0002d6000, 0xc0002d0000, 0xce5, 0x1032, 0x0, 0x0, 0x2, 0xc000483850, 0x93, 0x0, ...)
	/usr/local/go/src/regexp/regexp.go:616 +0x2e9
regexp.(*Regexp).ReplaceAllFunc(0xc0002d6000, 0xc0002d0000, 0xce5, 0x1032, 0xc000483948, 0x1032, 0xc0002bc240, 0x0)
	/usr/local/go/src/regexp/regexp.go:680 +0xbd
github.com/palantir/godel-format-asset-ptimports/generated_src/internal/github.com/palantir/go-ptimports/v2/ptimports.groupImports(0x7ffeefbff704, 0x6e, 0xc0001fc000, 0xce5, 0xfa2, 0xc0001fc000, 0xce5, 0xfa2, 0x0, 0x0)
	/go/src/github.com/palantir/godel-format-asset-ptimports/generated_src/internal/github.com/palantir/go-ptimports/v2/ptimports/imports.go:188 +0x315
github.com/palantir/godel-format-asset-ptimports/generated_src/internal/github.com/palantir/go-ptimports/v2/ptimports.Process(0x7ffeefbff704, 0x6e, 0xc0001ac000, 0xce5, 0x1e00, 0xc000483b68, 0x0, 0x0, 0x1d2, 0x0, ...)
	/go/src/github.com/palantir/godel-format-asset-ptimports/generated_src/internal/github.com/palantir/go-ptimports/v2/ptimports/imports.go:125 +0x1c0
github.com/palantir/godel-format-asset-ptimports/generated_src/internal/github.com/palantir/go-ptimports/v2/ptimports.ProcessFileFromInput(0x7ffeefbff704, 0x6e, 0x0, 0x0, 0xc0000a0100, 0xc000483b68, 0x164d260, 0xc0000a0008, 0x0, 0x0)
	/go/src/github.com/palantir/godel-format-asset-ptimports/generated_src/internal/github.com/palantir/go-ptimports/v2/ptimports/imports.go:58 +0x128
github.com/palantir/godel-format-asset-ptimports/generated_src/internal/github.com/palantir/go-ptimports/v2/cmd.glob..func1(0x19b9480, 0xc0002ac000, 0x58, 0x5b, 0x0, 0x0)
	/go/src/github.com/palantir/godel-format-asset-ptimports/generated_src/internal/github.com/palantir/go-ptimports/v2/cmd/root.go:41 +0x178
github.com/spf13/cobra.(*Command).execute(0x19b9480, 0xc0000b2010, 0x5b, 0x5f, 0x19b9480, 0xc0000b2010)
	/go/src/github.com/palantir/godel-format-asset-ptimports/vendor/github.com/spf13/cobra/command.go:756 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x19b9480, 0xc000260750, 0x30, 0xc0002083c0)
	/go/src/github.com/palantir/godel-format-asset-ptimports/vendor/github.com/spf13/cobra/command.go:846 +0x2ea
github.com/palantir/pkg/cobracli.Execute(0x19b9480, 0xc0002083c0, 0x4, 0x6, 0x0)
	/go/src/github.com/palantir/godel-format-asset-ptimports/vendor/github.com/palantir/pkg/cobracli/execute.go:30 +0xc8
github.com/palantir/pkg/cobracli.ExecuteWithDebugVarAndDefaultParams(0x19b9480, 0xc000202310, 0x0, 0x0, 0x0, 0xc00021c750)
	/go/src/github.com/palantir/godel-format-asset-ptimports/vendor/github.com/palantir/pkg/cobracli/default.go:36 +0x104
github.com/palantir/pkg/cobracli.ExecuteWithDefaultParams(...)
	/go/src/github.com/palantir/godel-format-asset-ptimports/vendor/github.com/palantir/pkg/cobracli/default.go:19
github.com/palantir/godel-format-asset-ptimports/generated_src/internal/github.com/palantir/go-ptimports/v2/cmd.Execute(...)
	/go/src/github.com/palantir/godel-format-asset-ptimports/generated_src/internal/github.com/palantir/go-ptimports/v2/cmd/root.go:60
github.com/palantir/godel-format-asset-ptimports/generated_src/internal/github.com/palantir/go-ptimports/v2.AmalgomatedMain()
	/go/src/github.com/palantir/godel-format-asset-ptimports/generated_src/internal/github.com/palantir/go-ptimports/v2/main.go:24 +0x58
github.com/palantir/godel-format-asset-ptimports/generated_src.glob..func1()
	/go/src/github.com/palantir/godel-format-asset-ptimports/generated_src/amalgomatedformatter.go:12 +0x20
github.com/palantir/godel-format-asset-ptimports/generated_src.(*amalgomated).Run(0x19e9f40, 0x157e0de, 0x9)
	/go/src/github.com/palantir/godel-format-asset-ptimports/generated_src/amalgomatedformatter.go:31 +0xa1
main.main()
	/go/src/github.com/palantir/godel-format-asset-ptimports/main.go:34 +0x159
```

## What did you want to happen?

Run `./godelw format`

## Note

I've forked the repo and will begin my best effort to resolve; however, I wanted to file the issue as soon as I discovered it.

**Comment by aarongreenlee** [comment]
I've forked the repo and will make a best effort to resolve.

**Comment by aarongreenlee** [comment]
I wonder if the dependency has changed in the dependency chain between `godel` and this package. I've isolated the syntax that causes a panic in the current version of `godel` but am unable to reproduce when I directly run the latest version of this package.

I believe the following syntax created the panic:

```
import "C"
import (
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"runtime"
	"sync"
	"time"
)
```

When I directly run `go run main.go -l -w $PATH_TO_FILE` no panic is reported. When I run `./godelw --format` for my project with the above syntax I observe the panic. When I remove the first import statement the panic does not occur.

Now, I am unsure how the first `import "C"` statement was added to my code as it does not make sense for the context of my file; however, I had committed the statement to my repo. I see this line https://github.com/palantir/go-ptimports/blob/master/ptimports/imports.go#L188 which appears to add it.

Anyway, I've removed the line `import "C"` which resolves the panic in `godel` and is sufficient for my needs now.

I hope this report is helpful if anyone else comes across this issue -- I'll close it at this time as I could not reproduce the panic in isolation.

## Thank you

Thank you for publishing these tools. I am finding them helpful on my personal project and I appreciate your contributions.
